### ISSUE TITLE
[13.0] hr_attendance_report_theoretical_time: Incompatibility with hr_expense

### ISSUE THREAD

**Issue by angelmoya** [OCA/hr-attendance#19]
You get an error creating expense report with employee without access to private addresses.

Steps to reproduce:
- Create a user without access to private addresses.
- Create employee for this user
- Create a expenses
- In expense form, save and click on "Create report" Button

![2020-11-11 08-01-53](https://user-images.githubusercontent.com/6750341/98780332-e1aaed80-23f4-11eb-975b-31c58640f2cb.png)

Error reason:

In hr standard module we have hr.employee and hr.employee.public, hr.employee.public is a sql view to get readonly acces to employee.

When you create a report with user without private addresses access you spect to get all fields created on hr.employee.

Maybe this is Odoo bug, and not bug on this report, but to prevent this error you can create this fields also in hr.employee.public.

**Comment by pedrobaeza** [comment]
Which OCA module?

**Comment by angelmoya** [comment]
At least:
- hr_attendance_report_theoretical_time, because add theoretical_hours_start_date on hr.employee and not on hr.employee.public
- hr_attendance_rfid, because add rfid_card_code on hr.employee and not on hr.employee.public

will fail with all field (no o2m, m2m or computed no stored) added to hr.employee and not on hr.employee.public

So, there are two sides to this matter:
1. It's a hr odoo module bug
2. It's a hr odoo module non feature, and OCA bug

**Comment by pedrobaeza** [comment]
Then please title properly the issue

**Comment by pedrobaeza** [comment]
They can be OCA bug due to the new model, but the solution is simple: move that fields from `hr.employee` to `hr.employee.public`.

**Comment by angelmoya** [comment]
Ok, thanks Pedro... I know solution si simple... Ok, I will fix, the question is:

Is really needed and well difened that all records present on hr.employee must be present on hr.employee.public?

Or is a Odoo hr_expense module bug?

**Comment by pedrobaeza** [comment]
I haven't dug enough to be able to say, Ángel. Maybe it's not and they have only tested the duality with non relational fields.

**Comment by pedrobaeza** [comment]
Shouldn't it be in `hr.employee.base` instead?

**Comment by pedrobaeza** [comment]
`hr_attendance_report_theoretical_time` fixed in #25

**Comment by victoralmau** [comment]
> `hr_attendance_report_theoretical_time` fixed in #25

IMO not solved yet, because although is similar, is related to `hr_attendance_rfid` addon (need to add fields in `hr.employee.public` too). Need to create other PR related it.

**Comment by pedrobaeza** [comment]
That error is for the other, not for the mentioned one.

**Comment by victoralmau** [comment]
`hr_attendance_rfid` fixed in https://github.com/OCA/hr-attendance/pull/27

**Comment by pedrobaeza** [comment]
Fixed
